name: cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev 

    - name: pnetcdf build
      run: |
        wget https://parallel-netcdf.github.io/Release/pnetcdf-1.12.1.tar.gz 
        tar -xzvf pnetcdf-1.12.1.tar.gz
        ls -l
        pushd pnetcdf-1.12.1
        ./configure --prefix=/usr --enable-shared --disable-cxx
        make
        sudo make install
        popd

    - name: cmake build
      run: |
        find /usr -name libnetcdf.so
        mkdir build
        cd build
        cmake -Wno-dev -DNetCDF_C_LIBRARY=/usr/lib/x86_64-linux-gnu/libnetcdf.so -DNetCDF_C_INCLUDE_DIR=/usr/include -DCMAKE_PREFIX_PATH=/usr -DPIO_HDF5_LOGGING=On -DPIO_USE_MALLOC=On -DPIO_ENABLE_LOGGING=On -DPIO_ENABLE_TIMING=Off ..
        make VERBOSE=1
        make tests VERBOSE=1
        ctest -VV
