
.. _Makefile:

####################################################
Makefile 
####################################################

**Makefile** is a script in CIMEROOT/scripts/Tools.

.. toctree::
   :maxdepth: 1

.. command-output:: ./Makefile --help
   :cwd: ../../../scripts/Tools
