#!/usr/bin/env perl
 
#--------------------------------------------------------------------------------------------
# build-namelist script for the CIME Data Runoff Model.
#--------------------------------------------------------------------------------------------

use strict;
use English;
use IO::File;

my ($caseroot, $cimeroot, $confdir, $inst_string, $namelist_infile, $user_xml_dir) = @ARGV;

my @dirs = ( "$cimeroot/utils/perl5lib" );
unshift @INC, @dirs;
require Streams::BuildNamelistUtils;

#-------------------------------------------
# Create nmlgen object
#-------------------------------------------

my $nmlgen = BuildNamelistUtils->new('drof',$cimeroot, $caseroot, $confdir, 
				     $user_xml_dir, $namelist_infile);

#-------------------------------------------
# Required xml variables           
#-------------------------------------------

my $DIN_LOC_ROOT = $nmlgen->get_xmlvar('DIN_LOC_ROOT');   
my $ROF_GRID	 = $nmlgen->get_xmlvar('ROF_GRID');	    
my $DROF_MODE	 = $nmlgen->get_xmlvar('DROF_MODE');	    

if (($ROF_GRID eq "null") && ($DROF_MODE ne "NULL")) {
    die "ERROR:: ROF_GRID null DROF_MODE not NULL.\n";
}

print "DROF mode is $DROF_MODE \n";
print "DROF grid is $ROF_GRID \n";

#-------------------------------------------
# Determine hash for parsing default_namelist_drof.xml
#-------------------------------------------
my %namelist_opts;
$namelist_opts{'drof_mode'} = $DROF_MODE;
$namelist_opts{'rof_grid'}  = $ROF_GRID;

#-------------------------------------------
# Determine streams
#-------------------------------------------

my @streams = $nmlgen->get_streams(\%namelist_opts );

#-------------------------------------------
# For each stream, create stream text file and update input data list
#-------------------------------------------

my $fh_out = new IO::File;
$fh_out->open(">$caseroot/Buildconf/drof.input_data_list") or
    die "** can't open filepath file: drof.input_data_list\n";

foreach my $stream ( @streams ) {
    if ($stream eq "NULL") {
	next;
    }
    print "DROF stream is $stream$inst_string \n";

    # Determine stream txt file and update the streams_namelists hash for the new stream
    my $outstream = "drof.streams.txt" . ".$stream" . "$inst_string";
    $nmlgen->create_stream_file(\%namelist_opts, $stream, $outstream, $fh_out);
}

$fh_out->close;

#-------------------------------------------
# namelist group: shr_strdata_nml  (in file drof_rof_in) 
#-------------------------------------------

$nmlgen->create_shr_strdata_nml(\%namelist_opts );

#FIXME - note that"${ROF_DOMAIN_PATH}/${ROF_DOMAIN_FILE}") is not sent as an argument
# to create_shr_strdata_nml and in fact domainfile does not appear in the namelist - WHY?

#-------------------------------------------
# namelist group: drof_nml  (in file drof_in)            
#-------------------------------------------

$nmlgen->add_default('rof_in', "drof_rof_in${inst_string}");
$nmlgen->add_default('decomp', '1d');
$nmlgen->add_default('force_prognostic_true', '.false.');
$nmlgen->add_default('restfilm', 'undefined');
$nmlgen->add_default('restfils', 'undefined');

#-------------------------------------------
# Write output files
#-------------------------------------------

$nmlgen->write_output_files('rof');
