if (NOT DEBUG)
  string(APPEND CFLAGS " -O -tp=skylake -Mnofma")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O -tp=skylake -Mnofma")
endif()
string(APPEND FFLAGS " -I$(EXEROOT)/ocn/obj/FMS")
if (NOT DEBUG)
  string(APPEND LDFLAGS " -O -tp=skylake -Mnofma -acc -ta=tesla:cc70,lineinfo,nofma -Minfo=accel")
endif()
string(APPEND SLIBS " -llapack -lblas")
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -ldl")
endif()
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -lnetcdf -lnetcdff")
