#!/usr/bin/env python3
# This script will print the list of test classes in
# scripts_regression_tests.py
#
import os
import unittest

os.chdir(os.path.dirname(__file__))

# pylint: disable=protected-access
def list_tests_from():

    suite = unittest.defaultTestLoader.discover(".")
    for test in suite:
        print(test._tests[0]._testMethodName)
        
if __name__ == "__main__":
    # Include the directories
    list_tests_from()
