#!/usr/bin/env perl

#-------------------------------------------------------------------------------------------
# build-namelist script for the CIME Data Ocean Model
#-------------------------------------------------------------------------------------------

use strict;
use English;
use IO::File;

my ($caseroot, $cimeroot, $confdir, $inst_string, $namelist_infile, $user_xml_dir) = @ARGV;

my @dirs = ( "$cimeroot/utils/perl5lib" );
unshift @INC, @dirs;
require Streams::BuildNamelistUtils;

#-------------------------------------------
# Create nmlgen object
#-------------------------------------------

my $nmlgen = BuildNamelistUtils->new('docn',$cimeroot, $caseroot, $confdir, 
				     $user_xml_dir, $namelist_infile);

#-------------------------------------------
# Required xml variables           
#-------------------------------------------

my $DIN_LOC_ROOT     = $nmlgen->get_xmlvar('DIN_LOC_ROOT');   
my $OCN_DOMAIN_FILE  = $nmlgen->get_xmlvar('OCN_DOMAIN_FILE');
my $OCN_DOMAIN_PATH  = $nmlgen->get_xmlvar('OCN_DOMAIN_PATH');
my $OCN_GRID         = $nmlgen->get_xmlvar('OCN_GRID');	    
my $DOCN_MODE        = $nmlgen->get_xmlvar('DOCN_MODE');	    
my $SSTICE_STREAM    = $nmlgen->get_xmlvar('SSTICE_STREAM');

print "DOCN mode is $DOCN_MODE \n";
print "DOCN grid is $OCN_GRID \n";

#-------------------------------------------
# Determine hash for parsing default_namelist_docn.xml
#-------------------------------------------
my %namelist_opts;
$namelist_opts{'docn_mode'}     = $DOCN_MODE;
$namelist_opts{'ocn_grid'}      = $OCN_GRID;
$namelist_opts{'sstice_stream'} = $SSTICE_STREAM;

#-------------------------------------------
# Determine streams
#-------------------------------------------

# Determine streams
my @streams = $nmlgen->get_streams(\%namelist_opts );

#-------------------------------------------
# For each stream, create stream text file and update input data list
#-------------------------------------------

my $fh_out = new IO::File;
$fh_out->open(">$caseroot/Buildconf/docn.input_data_list") or
    die "** can't open filepath file: docn.input_data_list\n";

foreach my $stream ( @streams ) {
    if ($stream eq "NULL") {
	next;
    }
    print "DOCN stream is $stream$inst_string \n";

    # Determine stream txt file and update the streams_namelists hash for the new stream
    my $outstream = "docn.streams.txt" . ".$stream" . "$inst_string";
    $nmlgen->create_stream_file(\%namelist_opts, $stream, $outstream, $fh_out);
}

$fh_out->close;

#-------------------------------------------
# namelist group: shr_strdata_nml
#-------------------------------------------

$nmlgen->create_shr_strdata_nml(\%namelist_opts, "${OCN_DOMAIN_PATH}/${OCN_DOMAIN_FILE}" );

#-------------------------------------------
# namelist group: docn_nml  (in file docn_in)            
#-------------------------------------------

$nmlgen->add_default('decomp', '1d');
$nmlgen->add_default('force_prognostic_true', '.false.');
$nmlgen->add_default('restfilm', 'undefined');
$nmlgen->add_default('restfils', 'undefined');

#-------------------------------------------
# Write output files
#-------------------------------------------

$nmlgen->write_output_files('ocn');

