#!/usr/bin/env python3

"""
Queries key CIME shell commands (mpirun and batch submission).

To force a certain mpirun command, use:
   ./xmlchange MPI_RUN_COMMAND=$your_cmd

Example:
   ./xmlchange MPI_RUN_COMMAND='mpiexec -np 16 --some-flag'

To force a certain qsub command, use:
   ./xmlchange --subgroup=case.run BATCH_COMMAND_FLAGS=$your_flags

Example:
   ./xmlchange --subgroup=case.run BATCH_COMMAND_FLAGS='--some-flag --other-flag'
"""

from standard_script_setup import *

from CIME.case import Case

logger = logging.getLogger(__name__)

###############################################################################
def parse_command_line(args, description):
    ###############################################################################
    parser = argparse.ArgumentParser(
        description=description, formatter_class=argparse.RawTextHelpFormatter
    )

    CIME.utils.setup_standard_logging_options(parser)

    parser.add_argument(
        "caseroot",
        nargs="?",
        default=os.getcwd(),
        help="Case directory to query.\n" "Default is current directory.",
    )

    parser.add_argument(
        "-j",
        "--job",
        default=None,
        help="The job you want to print.\n"
        "Default is case.run (or case.test if this is a test).",
    )

    args = CIME.utils.parse_args_and_handle_standard_logging_options(args, parser)

    return args.caseroot, args.job


###############################################################################
def _main_func(description):
    ###############################################################################
    caseroot, job = parse_command_line(sys.argv, description)
    logging.disable(logging.INFO)

    with Case(caseroot, read_only=False) as case:
        case.preview_run(print, job)


if __name__ == "__main__":
    _main_func(__doc__)
