string(APPEND CFLAGS " -qfloat=nomaf")
string(APPEND FFLAGS " -qfloat=nomaf")
set(HDF5_PATH "$ENV{HDF5}")
set(LD "/home/pkcoff/mpich-sandboxes/master/install-production/bin/mpixlf77_r")
set(MPICC "/home/pkcoff/mpich-sandboxes/master/install-production/bin/mpixlc_r")
set(MPIFC "/home/pkcoff/mpich-sandboxes/master/install-production/bin/mpixlf2003_r")
set(NETCDF_PATH "/soft/libraries/netcdf/4.3.3-f4.4.1/cnk-xl/current/")
set(PIO_FILESYSTEM_HINTS "gpfs")
set(PNETCDF_PATH "/soft/libraries/pnetcdf/1.6.1/cnk-xl/current/")
set(SCC "/home/pkcoff/mpich-sandboxes/master/install-production/bin/mpixlc_r")
set(SFC "/home/pkcoff/mpich-sandboxes/master/install-production/bin/mpixlf2003_r")
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -lnetcdff -lnetcdf -L$ENV{HDF5}/lib -lhdf5_hl -lhdf5 -L/soft/libraries/alcf/current/xl/ZLIB/lib -lz -L/soft/libraries/alcf/current/xl/LAPACK/lib -llapack -L/soft/libraries/alcf/current/xl/BLAS/lib -lblas -L/bgsys/drivers/ppcfloor/comm/sys/lib")
