set(CONFIG_ARGS "--build=powerpc-bgp-linux --host=powerpc64-suse-linux")
string(APPEND CPPDEFS " -DLINUX")
string(APPEND FFLAGS " -g -qfullpath -qmaxmem=-1 -qspillsize=2500 -qextname=flush")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O3 -qstrict -qinline=auto")
endif()
if (NOT DEBUG AND compile_threaded)
endif()
if (DEBUG AND compile_threaded)
endif()
set(LDFLAGS "-Wl,--relax -Wl,--allow-multiple-definition")
