string(APPEND CFLAGS " -lifcore")
string(APPEND FFLAGS " -lifcore")
if (MPILIB STREQUAL mpi-serial)
  string(APPEND FFLAGS " -mcmodel medium")
endif()
string(APPEND LDFLAGS " -lquadmath")
string(APPEND LDFLAGS " -Wl,-rpath,${NETCDF_PATH}/lib")
string(APPEND LDFLAGS " -Wl,-rpath,$ENV{COMPILER_PATH}/lib/intel64")
string(APPEND LDFLAGS " -Wl,-rpath,$ENV{COMPILER_PATH}/mkl/lib/intel64")
string(APPEND LDFLAGS " -Wl,-rpath,$ENV{MPI_PATH}/lib")
string(APPEND LDFLAGS " -lifcore")
if (MPILIB STREQUAL mvapich2)
endif()
if (MPILIB STREQUAL mpi-serial AND NOT compile_threaded)
  set(PFUNIT_PATH "/fs/cgd/csm/tools/pFUnit/pFUnit3.2.8_hobart_Intel15.0.2_noMPI_noOpenMP")
endif()
