set(AR "xiar")
set(ARFLAGS "cru")
if (MPILIB STREQUAL mpi-serial)
  string(APPEND FFLAGS " -mcmodel medium")
  string(APPEND FFLAGS " -mkl -xSKYLAKE-AVX512 -qopt-zmm-usage=high -no-fma")
  string(APPEND CFLAGS " -mkl -xSKYLAKE-AVX512 -qopt-zmm-usage=high -no-fma")
  string(APPEND LDFLAGS " -mkl -lstdc++")
  string(APPEND SLIBS " -lstdc++")
endif()
if (MPILIB STREQUAL impi)
  string(APPEND FFLAGS " -mkl=cluster -xSKYLAKE-AVX512 -qopt-zmm-usage=high -no-fma")
  string(APPEND CFLAGS " -mkl=cluster -xSKYLAKE-AVX512 -qopt-zmm-usage=high -no-fma")
  string(APPEND LDFLAGS " -mkl=cluster")
  string(APPEND SLIBS " -lstdc++")
endif()
set(MPICC "mpiicc")
set(MPICXX "mpiicpc")
set(MPIFC "mpiifort")
