string(APPEND CFLAGS " -qopt-report -xCORE_AVX2 -no-fma")
string(APPEND FFLAGS " -qopt-report -xCORE_AVX2 -no-fma")
if (DEBUG)
  string(APPEND CMAKE_OPTS " -DPIO_ENABLE_LOGGING=ON")
endif()
if (MPILIB STREQUAL mpi-serial AND NOT compile_threaded)
  set(PFUNIT_PATH "$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_noMPI_noOpenMP")
endif()
if (MPILIB STREQUAL mpt AND compile_threaded)
  set(PFUNIT_PATH "$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit3.2.8_cheyenne_Intel17.0.1_MPI_openMP")
endif()
set(HAS_F2008_CONTIGUOUS "TRUE")
