string(APPEND CFLAGS " -gopt  -time")
if (compile_threaded)
  string(APPEND CFLAGS " -mp")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_SHR_VMATH -DNO_R16  -DCPRPGI")
set(CXX_LINKER "CXX")
set(FC_AUTO_R8 "-r8")
string(APPEND FFLAGS " -i4 -gopt  -time -Mextend -byteswapio -Mflushz -Kieee")
if (compile_threaded)
  string(APPEND FFLAGS " -mp")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -O0 -g -Ktrap=fp -Mbounds -Kieee")
endif()
if (MODEL STREQUAL datm)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (MODEL STREQUAL dlnd)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (MODEL STREQUAL drof)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (MODEL STREQUAL dwav)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (MODEL STREQUAL dice)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (MODEL STREQUAL docn)
  string(APPEND FFLAGS " -Mnovect")
endif()
set(FFLAGS_NOOPT "-O0")
set(FIXEDFLAGS "-Mfixed")
set(FREEFLAGS "-Mfree")
set(HAS_F2008_CONTIGUOUS "FALSE")
set(LDFLAGS "-time -Wl,--allow-multiple-definition")
if (compile_threaded)
  string(APPEND LDFLAGS " -mp")
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "pgcc")
set(SCXX "pgc++")
set(SFC "pgf95")
