if (NOT DEBUG)
  string(APPEND CFLAGS " -O0")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O0")
endif()
string(APPEND LDFLAGS " -lgomp")
string(APPEND LDFLAGS " -Wl,-R${NETCDF_PATH}/lib")
string(APPEND LDFLAGS " -Wl,-R$ENV{COMPILER_PATH}/lib")
string(APPEND LDFLAGS " -Wl,-R$ENV{COMPILER_PATH}/libso")
