string(APPEND CPPDEFS " -DCESMCOUPLED")
if (COMP_NAME STREQUAL pop)
  string(APPEND CPPDEFS " -D_USE_FLOW_CONTROL")
endif()
if (COMP_NAME STREQUAL ufsatm)
  string(APPEND CPPDEFS " -DSPMD")
endif()
if (COMP_NAME STREQUAL ufsatm)
  string(APPEND INCLDIR " -I$(EXEROOT)/atm/obj/FMS")
endif()
if (COMP_NAME STREQUAL ufsatm)
  string(APPEND FFLAGS " $(FC_AUTO_R8)")
endif()
if (COMP_NAME STREQUAL mom)
  string(APPEND FFLAGS " $(FC_AUTO_R8) ")
  string(APPEND CPPDEFS " -Duse_LARGEFILE")
endif()
set(SUPPORTS_CXX "FALSE")
