#!/usr/bin/env python3

import os
import sys

real_file_dir = os.path.dirname(os.path.realpath(__file__))
cimeroot = os.path.abspath(os.path.join(real_file_dir, ".."))

sys.path.insert(0, cimeroot)

from CIME.scripts.create_clone import _main_func

if __name__ == "__main__":
    _main_func()
