#!/usr/bin/env python3

import os
import sys

real_file_dir = os.path.dirname(os.path.realpath(__file__))
cimeroot = os.path.abspath(os.path.join(real_file_dir, ".."))
# Set tools path as well so external scripts can import either
# CIME.Tools.standard_script_setup or just standard_script_setup
tools_path = os.path.join(cimeroot, "CIME", "Tools")

sys.path.insert(0, cimeroot)
sys.path.insert(1, tools_path)

from CIME.scripts.create_clone import _main_func

if __name__ == "__main__":
    _main_func()
