#!/usr/bin/env perl

#-------------------------------------------------------------------------------------------
# build-namelist script for the CIME Data Land Model
#-------------------------------------------------------------------------------------------

use strict;
use English;
use IO::File;

my ($caseroot, $cimeroot, $confdir, $inst_string, $namelist_infile, $user_xml_dir) = @ARGV;

my @dirs = ( "$cimeroot/utils/perl5lib" );
unshift @INC, @dirs;
require Streams::BuildNamelistUtils;

#-------------------------------------------
# Create nmlgen object
#-------------------------------------------

my $nmlgen = BuildNamelistUtils->new('dlnd',$cimeroot, $caseroot, $confdir, 
				     $user_xml_dir, $namelist_infile);

#-------------------------------------------
# Required xml variables           
#-------------------------------------------

my $DIN_LOC_ROOT     = $nmlgen->get_xmlvar('DIN_LOC_ROOT');   
my $LND_DOMAIN_FILE  = $nmlgen->get_xmlvar('LND_DOMAIN_FILE');
my $LND_DOMAIN_PATH  = $nmlgen->get_xmlvar('LND_DOMAIN_PATH');
my $LND_GRID         = $nmlgen->get_xmlvar('LND_GRID');	    
my $DLND_MODE        = $nmlgen->get_xmlvar('DLND_MODE');	    
my $GLC_NEC          = $nmlgen->get_xmlvar('GLC_NEC');        

print "DLND mode    is $DLND_MODE \n"; 
print "DLND grid    is $LND_GRID \n"; 
print "DLND glc_nec is $GLC_NEC \n"; 

#-------------------------------------------
# Determine hash for parsing default_namelist_dlnd.xml
#-------------------------------------------
my %namelist_opts;
$namelist_opts{'dlnd_mode'} = $DLND_MODE;
$namelist_opts{'lnd_grid'}  = $LND_GRID;

#-------------------------------------------
# Determine streams
#-------------------------------------------

# Determine streams
my @streams = $nmlgen->get_streams(\%namelist_opts );

#-------------------------------------------
# For each stream, create stream text file and update input data list
#-------------------------------------------

my $fh_out = new IO::File;
$fh_out->open(">$caseroot/Buildconf/dlnd.input_data_list") or
    die "** can't open filepath file: dlnd.input_data_list\n";

foreach my $stream ( @streams ) {
    if ($stream eq "NULL") {
	next;
    }
    print "DLND stream is $stream$inst_string \n";

    # Determine stream txt file and update the streams_namelists hash for the new stream
    my $outstream = "dlnd.streams.txt" . ".$stream" . "$inst_string";
    $nmlgen->create_stream_file(\%namelist_opts, $stream, $outstream, $fh_out);
}

$fh_out->close;

#-------------------------------------------
# namelist group: shr_strdata_nml  (in file dlnd_lnd_in) 
#-------------------------------------------

$nmlgen->create_shr_strdata_nml(\%namelist_opts, "${LND_DOMAIN_PATH}/${LND_DOMAIN_FILE}" );

#-------------------------------------------
# namelist group: dlnd_nml  (in file dlnd_in)            
#-------------------------------------------

$nmlgen->add_default('lnd_in' , "dlnd_lnd_in${inst_string}");
$nmlgen->add_default('decomp', '1d');
$nmlgen->add_default('force_prognostic_true', '.false.');
$nmlgen->add_default('restfilm',  'undefined');
$nmlgen->add_default('restfils',  'undefined');

#-------------------------------------------
# Write output files
#-------------------------------------------

$nmlgen->write_output_files('lnd');
