#!/usr/bin/env perl

#-------------------------------------------------------------------------------------------
# build-namelist script for the CIME Data Ice Model
#-------------------------------------------------------------------------------------------

use strict;
use English;
use IO::File;

my ($caseroot, $cimeroot, $confdir, $inst_string, $namelist_infile, $user_xml_dir) = @ARGV;

my @dirs = ( "$cimeroot/utils/perl5lib" );
unshift @INC, @dirs;
require Streams::BuildNamelistUtils;

#-------------------------------------------
# Create nmlgen object
#-------------------------------------------

my $nmlgen = BuildNamelistUtils->new('dice',$cimeroot, $caseroot, $confdir, 
				     $user_xml_dir, $namelist_infile);

#-------------------------------------------
# Required xml variables           
#-------------------------------------------

my $DIN_LOC_ROOT     = $nmlgen->get_xmlvar('DIN_LOC_ROOT');   
my $ICE_DOMAIN_FILE  = $nmlgen->get_xmlvar('ICE_DOMAIN_FILE');
my $ICE_DOMAIN_PATH  = $nmlgen->get_xmlvar('ICE_DOMAIN_PATH');
my $ICE_GRID         = $nmlgen->get_xmlvar('ICE_GRID');	    
my $DICE_MODE        = $nmlgen->get_xmlvar('DICE_MODE');	    

print "DICE mode is $DICE_MODE \n";
print "DICE grid is $ICE_GRID \n";

#-------------------------------------------
# Determine hash for parsing default_namelist_dice.xml
#-------------------------------------------
my %namelist_opts;
$namelist_opts{'dice_mode'} = $DICE_MODE;
$namelist_opts{'ice_grid'}  = $ICE_GRID;

#-------------------------------------------
# Determine streams
#-------------------------------------------

my @streams = $nmlgen->get_streams(\%namelist_opts );

#-------------------------------------------
# For each stream, create stream text file and update input data list
#-------------------------------------------

my $fh_out = new IO::File;
$fh_out->open(">$caseroot/Buildconf/dice.input_data_list") or
    die "** can't open filepath file: dice.input_data_list\n";

foreach my $stream ( @streams ) {
    if ($stream eq "NULL") {
	next;
    }
    print "DICE stream is $stream$inst_string \n";

    # Determine stream txt file and update the streams_namelists hash for the new stream
    my $outstream = "dice.streams.txt" . ".$stream" . "$inst_string";
    $nmlgen->create_stream_file(\%namelist_opts, $stream, $outstream, $fh_out);
}

$fh_out->close;

#-------------------------------------------
# namelist group: shr_strdata_nml
#-------------------------------------------

$nmlgen->create_shr_strdata_nml(\%namelist_opts, "${ICE_DOMAIN_PATH}/${ICE_DOMAIN_FILE}" );

#-------------------------------------------
# namelist group: dice_nml  
#-------------------------------------------

$nmlgen->add_default('flux_qacc'); #FIXME - is this right?

$nmlgen->add_default('decomp', '1d');
$nmlgen->add_default('force_prognostic_true', '.false.');
$nmlgen->add_default('restfilm', 'undefined');
$nmlgen->add_default('restfils', 'undefined');

#-------------------------------------------
# Write output files
#-------------------------------------------

$nmlgen->write_output_files('ice');
