name: cime testing

on:
  push:
    branches:
      - master
    paths:
      - 'CIME/**'
      - 'scripts/**'
      - 'tools/**'
      - 'utils/**'
      - 'docker/**'

  pull_request:
    branches:
      - master
    paths:
      - 'CIME/**'
      - 'scripts/**'
      - 'tools/**'
      - 'utils/**'
      - 'docker/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  packages: read

jobs:
  build-containers:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ESMCI/cime
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' }}
            type=ref,event=pr,enable=${{ github.event_name == 'pull_request' }}
            type=sha,format=long
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && ! cancelled() }}
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Runs pre-commit
        run: |
          pip install pre-commit
          pre-commit run -a

  # Runs unit testing under different python versions.
  unit-testing:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && always() && ! cancelled() }}
    needs: build-containers
    container:
      image: ghcr.io/esmci/cime:${{ github.event.pull_request.head.repo.full_name == github.repository && format('sha-{0}', github.sha) || 'latest' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
    steps:
      - name: Checkout CESM
        uses: actions/checkout@v4
        with:
          repository: https://github.com/ESCOMP/CESM.git
          ref: cesm3.0-alphabranch
          # $GITHUB_WORKSPACE/CESM
          path: CESM
      - name: Setup model
        run: |
          cd CESM
          git config --global --add safe.directory "*"
          ./bin/git-fleximod update
          git status
          git submodule status
          # remove CIME to checkout PR branch
          rm -rf cime
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: CESM/cime
          submodule: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        shell: bash
        env:
          CIME_MODEL: "cesm"
          CIME_DRIVER: "nuopc"
          CIME_TEST_PLATFORM: ubuntu-latest
        run: |
          python --version

          cd CESM/cime

          git config --global --add safe.directory "*"

          git status
          git submodule status

          pip install -r test-requirements.txt

          cp -rf /root/.cime /github/home

          ln -sf /github/home/.cime/config_machines.v3.xml /github/home/.cime/config_machines.xml

          python -vvv --cov=CIME --machine docker --no-fortran-run CIME/tests/test_unit*

  # Run system tests
  system-testing:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && always() && ! cancelled() }}
    needs: build-containers
    container:
      image: ghcr.io/esmci/cime:${{ github.event.pull_request.head.repo.full_name == github.repository && format('sha-{0}', github.sha) || 'latest' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --hostname docker
    strategy:
      # allow all jobs to finish
      fail-fast: false
      matrix:
        model:
          - name: e3sm
            repo: E3SM-Project/E3SM
            branch: master
          - name: cesm
            repo: ESCOMP/CESM
            branch: cesm3.0-alphabranch
        driver: ["mct", "nuopc"]
        exclude:
          # exclude nuopc driver when running e3sm tests
          - model: "e3sm"
            driver: "nuopc"
          # exclude mct driver when running cesm tests
          - model: "cesm"
            driver: "mct"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ matrix.model.name }}
      - name: Setup CESM model
        if: matrix.model.name == 'cesm'
        run: |
          cd ${{ matrix.model.name }}
          git config --global --add safe.directory "*"
          ./bin/git-fleximod update
          git status
          git submodule status
          # remove CIME to checkout PR branch
          rm -rf cime
      - name: Setup E3SM model
        if: matrix.model.name == 'e3sm'
        run: |
          cd ${{ matrix.model.name }}
          git config --global --add safe.directory "*"
          git submodule update --init
          source /helper.sh
          fix_mct_arflags $GITHUB_WORKSPACE/${{ matrix.model.name }}/externals/mct
          git status
          git submodule status
          # remove CIME to checkout PR branch
          rm -rf cime
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ matrix.model.name }}/cime
          submodule: true
      - name: Cache inputdata
        uses: actions/cache@v3
        with:
          path: /home/cime_user/output/inputdata
          key: inputdata-2
      - name: Run tests
        shell: bash
        env:
          CIME_MODEL: ${{ matrix.model.name }}
          CIME_DRIVER: ${{ matrix.driver }}
          CIME_TEST_PLATFORM: ubuntu-latest
        run: |
          cd ${{ matrix.model.name }}/cime

          pip install -r test-requirements.txt

          # GitHub runner home is different than container
          cp -rf /root/.cime /github/home/
          if [[ "${CIME_MODEL}" == "cesm" ]]; then
            ln -sf /github/home/.cime/config_machines.v3.xml /github/home/.cime/config_machines.xml
          else
            ln -sf /github/home/.cime/config_machines.v2.xml /github/home/.cime/config_machines.xml
          fi

          pytest -vvv --cov=CIME --machine docker --no-fortran-run --no-teardown CIME/tests/test_sys*
      - uses: mxschmitt/action-tmate@v3
        if: ${{ !always() }}
        with:
          limit-access-to-actor: true
      - name: Create testing log archive
        if: ${{ failure() }}
        shell: bash
        run: tar -czvf /testing-logs-${GITHUB_RUN_NUMBER}-${{ matrix.model.name }}-${{ matrix.driver }}.tar.gz /storage/cases/
        # How to download artifacts:
        # https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts
      - name: Upload testing logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: testing-logs-${{ github.run_number }}-${{ matrix.model.name }}-${{ matrix.driver }}
          path: /testing-logs-${{ github.run_number}}-${{ matrix.model.name }}-${{ matrix.driver }}.tar.gz
          retention-days: 4
